name: Deploy MP3Bat to Contabo

"on":
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  deploy:
    name: Deploy on Contabo
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          debug: true
          script: |
            /var/www/deploy-mp3bat.sh